version: '3'

networks:
  private:
  public:
    external:
      name: web
services:
  php:
    image: local/alfarioekaputra/laravel-php:7.4-apache
    labels:
      - traefik.backend=admin.compro
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:admin.compro.lokal
      - traefik.port=80
    networks:
      - private
      - public
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
